# Generated by Django 3.2 on 2022-04-28 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_auto_20220428_0331'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='happinessinfo',
            unique_together=set(),
        ),
    ]
