# Generated by Django 3.2 on 2022-04-28 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_alter_happinessinfo_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='happinessinfo',
            unique_together={('user', 'date')},
        ),
    ]
